apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    metadata:
      labels:
        environment: prod
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - catalog
              topologyKey: kubernetes.io/hostname
      containers:
        - name: catalog
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
