apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - monitoring-namespace.yaml
  - monitoring-release.yaml
configMapGenerator:
  - name: monitoring-values
    namespace: monitoring
    files:
      - values.yaml=../../values/monitoring.yaml
      - alerts.yaml=../../values/monitoring-alerts.yaml
