apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: catalog-test
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: retail-store-sample-app
  filterTags:
    pattern: "^test-.*$"
  policy:
    alphabetical:
      order: desc
  digestReflectionPolicy: IfNotPresent
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: catalog-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: retail-store-sample-app
  filterTags:
    pattern: "^staging-.*$"
  policy:
    alphabetical:
      order: desc
  digestReflectionPolicy: IfNotPresent
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: catalog-prod
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: retail-store-sample-app
  filterTags:
    pattern: "^prod-.*$"
  policy:
    alphabetical:
      order: desc
  digestReflectionPolicy: Always
  interval: 5m
