apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: retail-store-sample-staging
resources:
  - namespace.yaml
  - ../../base
images:
  - name: 339140803989.dkr.ecr.ap-southeast-1.amazonaws.com/aws-retail-store-sample-app
    newTag: staging-v1.0.2 # {"$imagepolicy": "flux-system:catalog-staging:tag"}
patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
