apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-store-sample-staging

resources:
  - namespace.yaml
  - ../../base

images:
  - name: aws-retail-store-sample-app
    newTag: staging # {"$imagepolicy": "flux-system:catalog-staging:tag"}

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
