apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  template:
    metadata:
      labels:
        environment: staging
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - catalog
                topologyKey: kubernetes.io/hostname
      containers:
        - name: catalog
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
